<?php

use Abacus\Currency;

class CurrencyTest extends PHPUnit_Framework_TestCase
{
    /**
     * Polls API
     *
     * Abacus must be able to get the latest exchange rates and add
     * them to the storage/exchange.json file. As the rest of the
     * application depends on the file generated by this action,
     * this method is done first.
     *
     */
    public function testPolls()
    {
        // Poll the API
        $result = Currency::update(getenv('ABACUS_OPEN_EXCHANGE_KEY'));

        // Abacus::update() returns the size of the file it created
        $this->assertInternalType('int', $result);

        // It should have make a file in this location
        $this->assertFileExists(sys_get_temp_dir() . "/abacus_exchange.json");
    }
}
